### PR TITLE
Maybe fix Dynamo?

### LINKED ISSUE #106: Installer causes Dynamo Revit 2.3 to freeze when dropping a BHoM component on an empty canvas
#### Description:
Works perfectly when compile Dynamo toolkit from Visual studio but not from installer. 
It also causes the Ctrl-Shift-B hotkey to have no effect.

#### Steps to reproduce:
Open Dynamo 2.3 in Revit 2020 and try to create a CreateCustom component on a new empty script.

See this issue for more details: https://github.com/BHoM/Dynamo_Toolkit/issues/278

From @adecler:

The `extra` folder is missing when running the installer:

image

This should look like this:

image

Not sure how the installer is set up but best to always copy the entire BHoM folder instead of individual subfolder in this case.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #106 maybe?

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
Seemed to work on my machine - will see what happens with this artefact when it finishes building...

**Review by pawelbaran — APPROVED** [review]
Maybe works for me - tested on Revit 2020 + Dynamo 2.3, no freeze. Maybe LGTM 👍

**Comment by FraserGreenroyd** [comment]
Hopefully @adecler will agree with the assessment @pawelbaran and I can remove the maybe from the title :smile:

**Review by adecler — APPROVED** [review]
All working for me now 👍

**Pull request merged**
