### PR TITLE
Include IES Extensions

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Resolves work around the IES Extensions workflow for @rboulton-BH @charliebrookerBH and @vbeardow

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by jamesramsden-bh — APPROVED** [review]
C:\ProgramData\BHoM\Extensions\IES created successfully, .py files created successfully. Tested against IES testing procedure, no problems.

**Pull request merged**
