### PR TITLE
Add altConfig for Lusas200

### LINKED ISSUE #185: Add altConfig for Lusas200
#### Parent issue(s) or Pull Request(s) causing the changes:

https://github.com/BHoM/Lusas_Toolkit/pull/359

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/Lusas_Toolkit/pull/359
   
### Issues addressed by this PR

Closes #185

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot run copyright-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check installer

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
This PR should be rebased to the latest main, owing to the following change being introduced:

 - All included repositories are now housed in a folder called `IncludedRepos` to tidy up the repository
 - This has included `altConfigs.txt` which this PR is modifying

A rebase should be sufficient hopefully, though the change may need to be made to the new file but hopefully not.

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: installer

**Review by FraserGreenroyd — APPROVED** [review]
Lusas PR has been merged so merging this to deploy.

**Pull request merged**
