### PR TITLE
Added alternate configurations for LusasV19

### LINKED ISSUE #83: Add Lusas19 Build and Debug configurations
#### Parent issue(s) or Pull Request(s) causing the changes:

https://github.com/BHoM/Lusas_Toolkit/issues/273

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/Lusas_Toolkit/pull/275
   
### Issues addressed by this PR

Closes #83 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Es_WPuwrP4dPlSS6VpNbKR8B6SlGv1QSKwohkY6zmjXDAA?e=Xjnns8

### Additional comments

@FraserGreenroyd I will let you know when to ~~release the hounds~~ create the artefact for testing (when the dependent PR is approved).

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd https://github.com/BHoM/Lusas_Toolkit/pull/275 has just been approved - could you please generate the artefact please.

**Review by StephennipBH — APPROVED** [review]
The changes work as intended. Changes approved.

**Review by FraserGreenroyd — APPROVED** [review]
Code changes are good, installer tested by discipline.

**Pull request merged**
