### PR TITLE
Include HTTP_Toolkit into the installer

### LINKED ISSUE #26: Include HTTP_Toolkit into the installer
#### Description:

As the title says - @SallyPickard FYI

### PR DESCRIPTION
**Pull request by epignatelli**
### Issues addressed by this PR

Closes #26 

### Questions

> The toolkit has a codeowners file outlining who is responsible for which parts of the code - this can be a global codeowners file with people taking responsibility for the whole toolkit, or it can be split by project/folder for multi-disciplinary toolkits
> Each toolkit should have a minimum of two codeowners to ensure there is redundancy for holidays, sickness, etc.

Does this mean that I should I add a CODEOWNER file as well?

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
> Does this mean that I should I add a CODEOWNER file as well?

Ah no I need to modify that part of the wiki, thanks for the reminder @epignatelli .

You do however need the following:

 - Suitable CI checks (currently you only have 1 of the required number)
 - Be compliant to current regulation - I'll run a report for you shortly and see whether there is anything major that would need doing

**Comment by FraserGreenroyd** [comment]
Ok so CI checks are now in so I am happy for this PR to be reviewed properly and merged as appropriate. Adding @awakeman to assist in reviewing

**Comment by epignatelli** [comment]
Thanks @FraserGreenroyd !

@BHoM/bhom_installer if all is ok for you, can we merge this, please?

**Comment by FraserGreenroyd** [comment]
I'm waiting for a second review to make sure @epignatelli But it will be merged today :smile:

**Pull request merged**
