### PR TITLE
Start of milestone changes for 8.1

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR
Uptick installer to 8.1

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check installer

**Review by michaelhoehn — APPROVED** [review]
Approved!

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: copyright-compliance

**Review by IsakNaslundBh — APPROVED** [review]
PRs have been reviewed by DevOps and are suitable for merge to uptick to the 8.1 milestone.

Reviewed together with
@pawelbaran

**Pull request merged**
