### PR TITLE
Inclusion of an IncludedDLLs file for installers

### LINKED ISSUE #130: Include an IncludedDLLs file with installations
To complement https://github.com/BHoM/BHoM_Engine/pull/2590 and https://github.com/BHoM/Grasshopper_Toolkit/issues/631

Needs to go into `C:\ProgramData\BHoM\Settings\`

FYI: @adecler

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #130 

### Test files
[Available here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FInstaller%2F%23131%2DIncludedDLLs)

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@adecler if you run the installer in the linked test folder (after cleaning your `C:/ProgramData/BHoM/Settings` folder) you should get the `IncludedDLLs.txt` file in that folder with the changes made in this PR.
If we're happy with this, we can then merge in the Engine and GH PRs tomorrow as well if you're in agreement :smile:
I've tested the artefact produced and was happy, hopefully you won't find any issues @adecler

**Review by adecler — APPROVED** [review]
Thanks @FraserGreenroyd ,

I just changed the filename reference in the Engine PR to match the casing (You use `DLL` while I was using `Dll`)

**Comment by FraserGreenroyd** [comment]
> I just changed the filename reference in the Engine PR to match the casing (You use `DLL` while I was using `Dll`)

Ah sorry, I must have been L/l blind yesterday.  Will take a quick re-review of the engine change for the no-file option, and then merge if all is ok so this can begin being deployed :smile:

**Pull request merged**
