### PR TITLE
Update folders to delete on install

### LINKED ISSUE #77: Modify Installer process to retain Logs and Settings on un/reinstall
#### Description:

On installing the BHoM - currently, by design, the process deletes the entire `%ProgramData%\BHoM` folder.

With move to have persistent machine settings and user configs, as well as logging system. Need to update the installer to delete the select folders within.

@adecler @FraserGreenroyd FYI

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #77

### CODE REVIEW

**Review by al-fisher — COMMENTED** [review]
Hi @FraserGreenroyd 
Tested asset on **install** and **remove**  and Logs and Settings folders are happily preserved.

Extensions (and it's content) is however removed. On uninstall.

This is _slightly_ outside the scope of this PR - so if we want to raise a separate issue around managing the Extensions folder - I am happy to approve.

**Comment by FraserGreenroyd** [comment]
image

I would argue it is in scope of this PR based on the above from the issue - I will take a look and report back

**Comment by FraserGreenroyd** [comment]
Having said that, I cannot see in the code where the Extensions folder would be removed.

image


This is the code handling it, and it's set specifically for the folders named - was this repeatable as an issue over a couple of uninstalls @al-fisher ?

**Comment by al-fisher** [comment]
Will re-test a couple of times now

**Comment by al-fisher** [comment]
Yes - can confirm - very repeatable. 
Left with just `\Logs` and `\Settings` after remove.
Do you get the same?

**Comment by FraserGreenroyd** [comment]
image

This is my folder structure following an uninstall, however the contents have been cleared but the folder structure all stays in place, but that's on a first attempt. Doing a second attempt now...

**Comment by FraserGreenroyd** [comment]
Second attempt has resulted in the same, intact folder structure but all empty of files.

Maybe given the timeline we're working to, and the extensions folder returning after reinstall this could be put into a new issue for further investigation owing to the other bits depending on this for the Analytics?

**Comment by al-fisher** [comment]
Yes - strange behaviour. But I am minded to log as separate issue as not critical (is mirroring at least the same, or better than, current installer behaviour)

**Comment by FraserGreenroyd** [comment]
In that case I think we're in agreement and can go for approval and merge with a new issue :smile:

**Review by al-fisher — APPROVED** [review]
Following discussion - approving and happy to merge subject to issue being raised for close out at later date regarding Extensions management. @FraserGreenroyd if you are happy to do that? 
Thanks!

**Comment by FraserGreenroyd** [comment]
@al-fisher issue #88 raised - going for merge now :smile:

**Pull request merged**
