### PR TITLE
Support for Revit 2024 added

### LINKED ISSUE #207: Add support for Revit 2024
#### Description:

See https://github.com/BHoM/Revit_Toolkit/issues/1428

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

https://github.com/BHoM/Revit_Toolkit/pull/1429

   
### Issues addressed by this PR

Closes #207

### Test files

Standard test procedure

### CODE REVIEW

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
The [previous PR](https://github.com/BHoM/BHoM_Installer/pull/164/files) for adding Revit 2023 had a few more files changed so I suspect we need them done here as well?

**Comment by pawelbaran** [comment]
Good shout @FraserGreenroyd, .wxs files should all be updated now 👍

**Review by FraserGreenroyd — APPROVED** [review]
All looks good to me now @pawelbaran - will merge and deploy and we can see how the alphas handle it

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: installer

**Pull request merged**
