### PR TITLE
Altconfigs for Revit added

### LINKED ISSUE #163: Revit 2023 support is missing
#### Description:

As in the title, Revit_Toolkit for 2023 is missing.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #163

### Test files

Run the installer, then run Revit 2023 and see if Revit_Toolkit is available.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by vietle-bh — APPROVED** [review]
Works great in my Revit 2023.

image

**Pull request merged**
