### PR TITLE
Removed Dynamo

### LINKED ISSUE #203: Removing Dynamo from the installer
Dynamo will not be included in BHoM and will need to be removed from the installer.

### PR DESCRIPTION
**Pull request by albinber**
### Issues addressed by this PR

Closes #203

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by Tom-Kingstone — APPROVED** [review]
Tested using an msi generated by @FraserGreenroyd - The installer correctly removes all BHoM packages from the Dynamo folder in `%AppData%/Roaming` and leaves any other files placed there alone.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
Tested the MSI generated by the bot and Dynamo is now removed on install and not added, without impacting the users existing Dynamo folders. Happy to deploy, thanks @albinber - great work!

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: installer

**Pull request merged**
