### PR TITLE
Add alternate configurations for Lusas_Toolkit builds

### LINKED ISSUE #50: Add configurations to build for Lusas_Toolkit
#### Description:

Add configurations to build for Lusas_Toolkit.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/Lusas_Toolkit/pull/253

### Issues addressed by this PR

Closes #50 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EnWHMty88w5PiJ0nLK_qJ-YBNLPTK9BFw-z5UuPo__IWRg?e=jhlHIN

### Additional comments

Julia if you could please run the installer in the link above and test Lusas 170.
@StephennipBH if you could please run the installer in the link above and test Lusas 180.

All the booleans are grouped on the far left, and should let you test:
- Push a variety of BHoMObjects to Lusas
- Pull a variety of BHoMObjects from Lusas
- Pull results from Lusas

**Note** You will need to modify the flexural mesh in Lusas once it has been pushed (I just edit one attribute and apply them to the TopChord and BottomChord groups). This is because it defaults to a Thick Cross Section Beam, when the element type should be a Thick Beam. This will be [fixed in this PR](https://github.com/BHoM/Lusas_Toolkit/pull/251). Once you solve the model you should be able to pull results.

Any questions let me know.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
To confirm following discussion with @peterjamesnugent , I will extract the artefact for him, and his team will test that the installer contains working versions of both builds. @peterjamesnugent will add the relevant Lusas reviewers to this PR, and once the artefact is ready (at time of writing it isn't), @peterjamesnugent will let us know for extraction :smile:

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd the time has come, extract the artefact please.

**Comment by JKarasinska** [comment]
The installer run successfully. I was able to push elements to Lusas, pull elements and pull results from Lusas with no issues.

**Pull request merged**
