### PR TITLE
Installer support for Revit_Toolkit v2022 added

### LINKED ISSUE #132: Add Revit_Toolkit 2022 assemblies to the installer
#### Description:

As in the title, nice to have as BHoM/Revit_Toolkit#1072 is being worked on.

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

https://github.com/BHoM/Revit_Toolkit/pull/1072

   
### Issues addressed by this PR

Closes #132

### Test files

Ideally I would like to see the installer with Revit_Toolkit v2022 landing in [this SharePoint folder](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231072%2DRevit2022Support&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Review by ssiimmoonnee — APPROVED** [review]
Tested in Revit 2022. It works!

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by FraserGreenroyd — COMMENTED** [review]
LGTM, approving in line with the other tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3525963603

**Review by FraserGreenroyd — APPROVED** [review]

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
