### PR TITLE
Add support for GSA 10 in installer

### LINKED ISSUE #165: Add support for GSA10.1 build to installer
#### Description:

As title says. Need to add alt config builds for GSA_Toolkit after merge of https://github.com/BHoM/GSA_Toolkit/pull/244

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/GSA_Toolkit/pull/268   

### Issues addressed by this PR

Closes #165

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am requesting a force check on: installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am requesting a force check on: installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am requesting a force check on: installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am requesting a force check on: installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am requesting a force check on: installer

**Comment by IsakNaslundBh** [comment]
@IsakNaslundBh I am now running force checks on the checks requested. These will be queued and actioned ASAP.

**Review by johannaisak — APPROVED** [review]
Tested, all working as expected

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
This is suitable to update the installer, and the functionality has been reviewed by @johannaisak so I'm happy from a DevOps perspective.

**Pull request merged**
